spring:
  application:
    name: ${record.service.name}
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/record_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  config:
    import: optional:file:../.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.service.host}:${eureka.service.port}/eureka

server:
  port: ${record.service.port}
